--- Makefile.old	2016-10-10 21:27:09.561629043 -0700
+++ Makefile	2016-10-10 21:36:21.060497349 -0700
@@ -14,6 +14,7 @@
 mem_gen = $(base_dir)/vsim/vlsi_mem_gen
 sim_dir = .
 output_dir = $(sim_dir)/output
+acc_verilog_dir = $(base_dir)/sha3-accel/src/main/verilog
 
 BACKEND ?= rocketchip.RocketChipBackend
 CONFIG ?= DefaultVLSIConfig
